apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: 1Gi # shouldn't be > PV storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  volumeName: mypv
