apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  labels:
    app.kubernetes.io/name: myapp
    env: dev
spec:
  containers:
    - name: my-nginx-container
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
  