apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - port: 4000 #ClusterIP port - internal cluster access
    targetPort: 80 # pod's actual listening port (nginx here) 
    nodePort: 30500 # external access point on every node's IP
